#this will build a java project with maven
name: Java CI with Maven
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{matrix.os}}	

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            additional-maven-args: "-Pjacoco -Pdocker -DrepoToken=$COVERALLS_REPO_TOKEN coveralls:report"
            jacoco-is-used: "-jacoco"
          #- os: macos-latest
          #- os: windows-latest

    name: Build with Java on ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: corretto
    - name: Cache m2 folder
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{runner.os}}-m2-${{hashFiles('**/pom.xml', '**/*.yaml')}}
        restore-keys: ${{runner.os}}-m2-
    - name: Build with Maven
      run: >
        mvn clean verify 
        ${{matrix.additional-maven-args}} 
        surefire-report:report-only site:site -DgenerateReports=false
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_TOKEN}} 
    - name: Archive Junit Report
      uses: actions/upload-artifact@v4
      with:
        name: surefire-report-${{runner.os}}${{matrix.jacoco-is-used}}
        path: '**/target/site'