#this will build a java project with maven
name: Java CI with Maven on windows
on:
  #push:
  #pull_request:

jobs:
  build:
    runs-on: ${{matrix.os}}	
    env:
      DOCKER_HOST: tcp://localhost:2375

    strategy:
      matrix:
        include:
          - os: windows-latest
            additional-maven-args: "-Pdocker"

    name: Build with Java on ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: corretto
  #  - name: Docker config
   #   run: >
    #    sc config docker
     #   binpath="dockerd.exe --run-service -H tcp://localhost:2375"
#    - name: Docker restart
 #     run: restart-service *docker*
  #  - name: Docker info
   #   run: docker info
    - name: Cache m2 folder
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{runner.os}}-m2-${{hashFiles('**/pom.xml', '**/*.yaml')}}
        restore-keys: ${{runner.os}}-m2-
    - name: Build with Maven
      run: >
        mvn clean verify 
        ${{matrix.additional-maven-args}} 
        surefire-report:report-only site:site -DgenerateReports=false 
 #     working-directory: com.examples.hellodocker
    - name: Archive Junit Report
      uses: actions/upload-artifact@v4
      with:
        name: surefire-report-${{runner.os}}
        path: '**/target/site'