#this will build a java project with maven
name: Java CI with Maven on mac
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    name: Build with Java on macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: corretto
    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master
    - name: Cache m2 folder
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: macos-latest-m2-${{hashFiles('**/pom.xml', '**/*.yaml')}}
        restore-keys: macos-latest-m2-
    - name: Build with Maven
      run: >
        mvn clean verify -Pdocker
        surefire-report:report-only site:site -DgenerateReports=false
      working-directory: com.example.App
    - name: Archive Junit Report
      uses: actions/upload-artifact@v4
      with:
        name: surefire-report-${{runner.os}}
        path: '**/target/site'