#this will build a java project with maven
name: Java CI with Maven on windows
on:
  push:
  #pull_request:

jobs:
  build:
    runs-on: windows-latest
    env:
      DOCKER_HOST: tcp://localhost:2375

    name: Build with Java on windows
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: corretto
    - name: Docker config
      run: >
        sc config docker
        binpath="dockerd.exe --run-service -H tcp://localhost:2375"
    - name: Docker restart
      run: restart-service *docker*
    - name: Docker info
      run: docker info
    - name: Cache m2 folder
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: windows-latest-m2-${{hashFiles('**/pom.xml', '**/*.yaml')}}
        restore-keys: windows-latest-m2-
    - name: Build with Maven
      run: >
        mvn clean verify 
        -Pdocker
        surefire-report:report-only site:site -DgenerateReports=false 
 #     working-directory: com.examples.hellodocker
    - name: Archive Junit Report
      uses: actions/upload-artifact@v4
      with:
        name: surefire-report-windows-latest
        path: '**/target/site'