#this will build a java project with maven
name: Java CI with Maven in Linux
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest		
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Build with Maven
      run: mvn clean verify